name = "Create Aestro"
author = "Spekac007"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f8f98a29db4af5f70f379f9444d05fe374a6c211891d858744010a8759f98890"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
