name = "Create Aestro"
author = "Spekac007"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ae28413e4b6f9fd6c17ba8b2df17bacc80cbd81c8763aa110eece81d2b462db"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
