name = "Create Aestro"
author = "Spekac007"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b304067f7dfc77f1c7927a7bd9258e6ec3d449f29585c4862393d1442a6eafa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.250"
